title: "Gennadii Iakovlev"
description: "Political scientist | Elite rhetoric, autocratization"
url: "https://gennadiiiakovlev.github.io"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"
plugins: [jekyll-feed, jekyll-seo-tag, jekyll-include-cache]
