title: "Gennadii Iakovlev"
description: "Political scientist | Text as Data, Large Language Models, Polarization, Autocratization"

keywords: text as data, natural language processing, large language models, artificial intelligence, text mining, polarization, autocratization, democratization, ai assisted research methods, big data

url: "https://gennadiiiakovlev.github.io"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"  # or @latest tag
minimal_mistakes_skin: "dark"
plugins: [jekyll-feed, jekyll-seo-tag, jekyll-include-cache, jekyll-remote-theme ]


# Site Author
author:
  name             : "Gennadii Iakovlev"
  avatar           : /assets/avatar.jpg
  location         : "Budapest, Hungary"
  email            : "gennadii.iakovlev@eui.eu"
  orcid_id: https://orcid.org/0000-0002-8355-6914

   

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/GennadiiIakovlev"
      # url:
    - label: "Google Scholar"
      url: "https://scholar.google.com/citations?hl=ru&user=jdpu-AgAAAAJ"
      # url:
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/gennadii-iakovlev/t"
