title: "Gennadii Iakovlev"
description: "Political scientist | Text as Data, Polarization, Autocratization"
url: "https://gennadiiiakovlev.github.io"
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"
plugins: [jekyll-feed, jekyll-seo-tag, jekyll-include-cache]
